const sagaTypes = Object.freeze({
  LOGIN_ASYNC: 'LOGIN_ASYNC',
  SIGNUP_ASYNC: 'SIGNUP_ASYNC',
  UPDATE_USER_PROFILE_ASYNC: 'UPDATE_USER_PROFILE_ASYNC',
  DELETE_ACCOUNT_ASYNC: 'DELETE_ACCOUNT_ASYNC',
  LOGOUT: 'LOGOUT',
});

export default sagaTypes;
