import type { Metadata } from 'next';
import Footer from '@src/components/Footer';
import Header from '@src/components/Header';
import { Inter } from 'next/font/google';
import { notFound, useRouter } from 'next/navigation';
import './globals.css';
import StoreProvider from './StoreProvider';
import { ToastContainer, toast } from 'react-toastify';
import cx from 'clsx';
import 'react-toastify/dist/ReactToastify.css';
import MobileNavBar, { IMenuItem } from '@src/components/MobileNavbar';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'NextTech',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='uk'>
      <body className={cx(inter.className, 'bg-white')}>
        <StoreProvider>
          <ToastContainer
            position='bottom-right'
            autoClose={3000}
            hideProgressBar={false}
            newestOnTop={false}
            closeOnClick
            rtl={false}
            pauseOnFocusLoss
            draggable
            pauseOnHover
            theme='light'
          />
          <div className='h-full flex flex-col'>
            <div className='w-full sticky left-0 top-0 z-50'>
              <Header />
            </div>
            <div className='flex-1'>{children}</div>
            <div className='block md:hidden w-full fixed left-0 bottom-0 bg-white z-40'>
              <MobileNavBar />
            </div>
            <Footer />
          </div>
        </StoreProvider>
      </body>
    </html>
  );
}
