import type { Metadata } from 'next';
import Footer from '@src/components/Footer';
import Header from '@src/components/Header';
import { Inter } from 'next/font/google';
import { notFound } from 'next/navigation';
import './globals.css';
import { NextIntlClientProvider, useMessages } from 'next-intl';
import StoreProvider from './StoreProvider';
import cx from 'clsx';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'NextTech',
  description: 'Generated by create next app',
};

const locales = ['uk', 'en'];

export default function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: any };
}) {
  const messages = useMessages();

  // Validate that the incoming `locale` parameter is valid
  if (!locales.includes(locale as any)) notFound();

  return (
    <html lang={locale}>
      <body className={cx(inter.className, 'bg-lightsecond')}>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <StoreProvider>
            <Header />
            {children}
            <Footer />
          </StoreProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
