import type { Metadata } from 'next'
import Footer from '@src/components/Footer'
import Header from '@src/components/Header'
import { Inter } from 'next/font/google'
import { notFound } from 'next/navigation'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'NextTech',
  description: 'Generated by create next app',
}

const locales = ['uk', 'en'];

export default function RootLayout({
  children,
  params: {
    locale,
  }
}: {
  children: React.ReactNode, params: { locale: any }
}) {

  // Validate that the incoming `locale` parameter is valid
  if (!locales.includes(locale as any)) notFound();

  return (
    <html lang={locale}>
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
        </body>
    </html>
  )
}
